### ISSUE TITLE
Build failure on master in Jenkins

### ISSUE THREAD

**Issue by alexgibson** [mozilla/protocol#284]
Builds of Protocol on Jenkins are [failing](https://ci.us-west.moz.works/blue/organizations/jenkins/protocol/detail/master/65/pipeline/) with the following error:

```
internal/util/inspect.js:31
const types = internalBinding('types');
              ^
ReferenceError: internalBinding is not defined
    at internal/util/inspect.js:31:15
    at req_ (/app/node_modules/natives/index.js:137:5)
    at require (/app/node_modules/natives/index.js:110:12)
    at util.js:25:21
    at req_ (/app/node_modules/natives/index.js:137:5)
    at require (/app/node_modules/natives/index.js:110:12)
    at fs.js:42:21
    at req_ (/app/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/app/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/app/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:99)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! protocol@3.1.0 build: `npm run prestart && gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the protocol@3.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-12-13T17_24_17_330Z-debug.log
script returned exit code 1
```

**Comment by alexgibson** [comment]
This was fixed in https://github.com/mozilla/protocol/commit/85390d619c7cbc776d757222a15f5e5985cb46ef
